apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: text-classifier-server
  annotations:
    scenarios.ai.sap.com/description: "Text Classification Service with Random Response"
    scenarios.ai.sap.com/name: "Text Classifier (Tutorial)"
    executables.ai.sap.com/description: "Create online server for text classification"
    executables.ai.sap.com/name: "Text Classification Server"
  labels:
    scenarios.ai.sap.com/id: "text-classifier-demo"
    ai.sap.com/version: "1.0"
spec:
  inputs:
    parameters:
      - name: greetmessage
        type: string
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-secret
        minReplicas: 1
        maxReplicas: 5
        containers:
        - name: kserve-container
          image: "docker.io/rugved88/global-classifier:latest"
          ports:
            - containerPort: 5000
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e && echo "Starting" && python /app/app.py
          env:
            - name: greetingmessage
              value: "{{inputs.parameters.greetmessage}}"
