apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  # Use a unique name for your AI Core instance
  name: po-classifier-template

  annotations:
    scenarios.ai.sap.com/description: "Rule-based PO classification, no input artifacts"
    scenarios.ai.sap.com/name: "PO Classifier (Minimal)"
    executables.ai.sap.com/description: "Multi-route + priority classification for POs"
    executables.ai.sap.com/name: "po-classifier-service"

  labels:
    scenarios.ai.sap.com/id: "po-classification"
    ai.sap.com/version: "1.0"

spec:
  # No input artifacts or parameters
  inputs:
    artifacts: []
    parameters: []

  template:
    # This must be 'serving.kserve.io/v1beta1' for SAP AI Core serving
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        # Docker registry secret reference (optional if public image)
        imagePullSecrets:
          - name: my-registry-secret
        minReplicas: 1
        maxReplicas: 5
        containers:
          - name: kserve-container
            # Replace this with your actual Docker image location
            image: "docker.io/rugved88/po-classifier:latest"
            ports:
              - containerPort: 9001
                protocol: TCP
            command: ["/bin/sh", "-c"]
            args:
              - >
                set -e &&
                echo "Starting container..." &&
                gunicorn --chdir /app/src main:app -b 0.0.0.0:9001
