apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: po-classifier-template
  annotations:
    scenarios.ai.sap.com/description: "PO classification with priority and type"
    scenarios.ai.sap.com/name: "PO Classifier"
    executables.ai.sap.com/description: "Classifies purchase orders"
    executables.ai.sap.com/name: "po-classifier-service"
  labels:
    scenarios.ai.sap.com/id: "po-classifier-demo"
    ai.sap.com/version: "1.0"
spec:
  inputs:
    artifacts: []
    parameters: []
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-secret
        minReplicas: 1
        maxReplicas: 5
        containers:
          - name: kserve-container
            image: "docker.io/rugved88/po-classifier:latest"
            ports:
              - containerPort: 9001
                protocol: TCP
            command: ["python"]
            args: ["main.py"]
